// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/gossip/v1/gossip.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Digest represents a compact summary of endpoint state
type GossipDigest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Generation    int64                  `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	MaxVersion    int64                  `protobuf:"varint,3,opt,name=max_version,json=maxVersion,proto3" json:"max_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipDigest) Reset() {
	*x = GossipDigest{}
	mi := &file_api_gossip_v1_gossip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipDigest) ProtoMessage() {}

func (x *GossipDigest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gossip_v1_gossip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipDigest.ProtoReflect.Descriptor instead.
func (*GossipDigest) Descriptor() ([]byte, []int) {
	return file_api_gossip_v1_gossip_proto_rawDescGZIP(), []int{0}
}

func (x *GossipDigest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GossipDigest) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *GossipDigest) GetMaxVersion() int64 {
	if x != nil {
		return x.MaxVersion
	}
	return 0
}

// Phase 1: SYN - Initiator sends digests of all known endpoints
type GossipDigestSynMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Digests       []*GossipDigest        `protobuf:"bytes,2,rep,name=digests,proto3" json:"digests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipDigestSynMsg) Reset() {
	*x = GossipDigestSynMsg{}
	mi := &file_api_gossip_v1_gossip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipDigestSynMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipDigestSynMsg) ProtoMessage() {}

func (x *GossipDigestSynMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_gossip_v1_gossip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipDigestSynMsg.ProtoReflect.Descriptor instead.
func (*GossipDigestSynMsg) Descriptor() ([]byte, []int) {
	return file_api_gossip_v1_gossip_proto_rawDescGZIP(), []int{1}
}

func (x *GossipDigestSynMsg) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *GossipDigestSynMsg) GetDigests() []*GossipDigest {
	if x != nil {
		return x.Digests
	}
	return nil
}

// ApplicationState represents a piece of versioned application state
type ApplicationState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // e.g., "STATUS", "ADDR"
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationState) Reset() {
	*x = ApplicationState{}
	mi := &file_api_gossip_v1_gossip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationState) ProtoMessage() {}

func (x *ApplicationState) ProtoReflect() protoreflect.Message {
	mi := &file_api_gossip_v1_gossip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationState.ProtoReflect.Descriptor instead.
func (*ApplicationState) Descriptor() ([]byte, []int) {
	return file_api_gossip_v1_gossip_proto_rawDescGZIP(), []int{2}
}

func (x *ApplicationState) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ApplicationState) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ApplicationState) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// EndpointState represents complete state for a node
type EndpointState struct {
	state             protoimpl.MessageState       `protogen:"open.v1"`
	NodeId            string                       `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Generation        int64                        `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	Version           int64                        `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	ApplicationStates map[string]*ApplicationState `protobuf:"bytes,4,rep,name=application_states,json=applicationStates,proto3" json:"application_states,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UpdateTimestamp   int64                        `protobuf:"varint,5,opt,name=update_timestamp,json=updateTimestamp,proto3" json:"update_timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EndpointState) Reset() {
	*x = EndpointState{}
	mi := &file_api_gossip_v1_gossip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointState) ProtoMessage() {}

func (x *EndpointState) ProtoReflect() protoreflect.Message {
	mi := &file_api_gossip_v1_gossip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointState.ProtoReflect.Descriptor instead.
func (*EndpointState) Descriptor() ([]byte, []int) {
	return file_api_gossip_v1_gossip_proto_rawDescGZIP(), []int{3}
}

func (x *EndpointState) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *EndpointState) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *EndpointState) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *EndpointState) GetApplicationStates() map[string]*ApplicationState {
	if x != nil {
		return x.ApplicationStates
	}
	return nil
}

func (x *EndpointState) GetUpdateTimestamp() int64 {
	if x != nil {
		return x.UpdateTimestamp
	}
	return 0
}

// Phase 2: ACK - Peer responds with states and requests
type GossipDigestAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// States the peer has that the initiator needs
	EndpointStates []*EndpointState `protobuf:"bytes,1,rep,name=endpoint_states,json=endpointStates,proto3" json:"endpoint_states,omitempty"`
	// Digests of states the peer needs from the initiator
	RequestDigests []*GossipDigest `protobuf:"bytes,2,rep,name=request_digests,json=requestDigests,proto3" json:"request_digests,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GossipDigestAck) Reset() {
	*x = GossipDigestAck{}
	mi := &file_api_gossip_v1_gossip_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipDigestAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipDigestAck) ProtoMessage() {}

func (x *GossipDigestAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_gossip_v1_gossip_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipDigestAck.ProtoReflect.Descriptor instead.
func (*GossipDigestAck) Descriptor() ([]byte, []int) {
	return file_api_gossip_v1_gossip_proto_rawDescGZIP(), []int{4}
}

func (x *GossipDigestAck) GetEndpointStates() []*EndpointState {
	if x != nil {
		return x.EndpointStates
	}
	return nil
}

func (x *GossipDigestAck) GetRequestDigests() []*GossipDigest {
	if x != nil {
		return x.RequestDigests
	}
	return nil
}

// Phase 3: ACK2 - Initiator sends requested states
type GossipDigestAck2 struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EndpointStates []*EndpointState       `protobuf:"bytes,1,rep,name=endpoint_states,json=endpointStates,proto3" json:"endpoint_states,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GossipDigestAck2) Reset() {
	*x = GossipDigestAck2{}
	mi := &file_api_gossip_v1_gossip_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipDigestAck2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipDigestAck2) ProtoMessage() {}

func (x *GossipDigestAck2) ProtoReflect() protoreflect.Message {
	mi := &file_api_gossip_v1_gossip_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipDigestAck2.ProtoReflect.Descriptor instead.
func (*GossipDigestAck2) Descriptor() ([]byte, []int) {
	return file_api_gossip_v1_gossip_proto_rawDescGZIP(), []int{5}
}

func (x *GossipDigestAck2) GetEndpointStates() []*EndpointState {
	if x != nil {
		return x.EndpointStates
	}
	return nil
}

var File_api_gossip_v1_gossip_proto protoreflect.FileDescriptor

const file_api_gossip_v1_gossip_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/gossip/v1/gossip.proto\x121github.adamgarcia4.golearning.cassandra.gossip.v1\"h\n" +
	"\fGossipDigest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x03R\n" +
	"generation\x12\x1f\n" +
	"\vmax_version\x18\x03 \x01(\x03R\n" +
	"maxVersion\"\x8e\x01\n" +
	"\x12GossipDigestSynMsg\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12Y\n" +
	"\adigests\x18\x02 \x03(\v2?.github.adamgarcia4.golearning.cassandra.gossip.v1.GossipDigestR\adigests\"T\n" +
	"\x10ApplicationState\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"\xa2\x03\n" +
	"\rEndpointState\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x03R\n" +
	"generation\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x86\x01\n" +
	"\x12application_states\x18\x04 \x03(\v2W.github.adamgarcia4.golearning.cassandra.gossip.v1.EndpointState.ApplicationStatesEntryR\x11applicationStates\x12)\n" +
	"\x10update_timestamp\x18\x05 \x01(\x03R\x0fupdateTimestamp\x1a\x89\x01\n" +
	"\x16ApplicationStatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12Y\n" +
	"\x05value\x18\x02 \x01(\v2C.github.adamgarcia4.golearning.cassandra.gossip.v1.ApplicationStateR\x05value:\x028\x01\"\xe6\x01\n" +
	"\x0fGossipDigestAck\x12i\n" +
	"\x0fendpoint_states\x18\x01 \x03(\v2@.github.adamgarcia4.golearning.cassandra.gossip.v1.EndpointStateR\x0eendpointStates\x12h\n" +
	"\x0frequest_digests\x18\x02 \x03(\v2?.github.adamgarcia4.golearning.cassandra.gossip.v1.GossipDigestR\x0erequestDigests\"}\n" +
	"\x10GossipDigestAck2\x12i\n" +
	"\x0fendpoint_states\x18\x01 \x03(\v2@.github.adamgarcia4.golearning.cassandra.gossip.v1.EndpointStateR\x0eendpointStates2\xae\x01\n" +
	"\rGossipService\x12\x9c\x01\n" +
	"\x0fGossipDigestSyn\x12E.github.adamgarcia4.golearning.cassandra.gossip.v1.GossipDigestSynMsg\x1aB.github.adamgarcia4.golearning.cassandra.gossip.v1.GossipDigestAckB;Z9github.com/adamgarcia4/goLearning/cassandra/api/gossip/v1b\x06proto3"

var (
	file_api_gossip_v1_gossip_proto_rawDescOnce sync.Once
	file_api_gossip_v1_gossip_proto_rawDescData []byte
)

func file_api_gossip_v1_gossip_proto_rawDescGZIP() []byte {
	file_api_gossip_v1_gossip_proto_rawDescOnce.Do(func() {
		file_api_gossip_v1_gossip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gossip_v1_gossip_proto_rawDesc), len(file_api_gossip_v1_gossip_proto_rawDesc)))
	})
	return file_api_gossip_v1_gossip_proto_rawDescData
}

var file_api_gossip_v1_gossip_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_gossip_v1_gossip_proto_goTypes = []any{
	(*GossipDigest)(nil),       // 0: github.adamgarcia4.golearning.cassandra.gossip.v1.GossipDigest
	(*GossipDigestSynMsg)(nil), // 1: github.adamgarcia4.golearning.cassandra.gossip.v1.GossipDigestSynMsg
	(*ApplicationState)(nil),   // 2: github.adamgarcia4.golearning.cassandra.gossip.v1.ApplicationState
	(*EndpointState)(nil),      // 3: github.adamgarcia4.golearning.cassandra.gossip.v1.EndpointState
	(*GossipDigestAck)(nil),    // 4: github.adamgarcia4.golearning.cassandra.gossip.v1.GossipDigestAck
	(*GossipDigestAck2)(nil),   // 5: github.adamgarcia4.golearning.cassandra.gossip.v1.GossipDigestAck2
	nil,                        // 6: github.adamgarcia4.golearning.cassandra.gossip.v1.EndpointState.ApplicationStatesEntry
}
var file_api_gossip_v1_gossip_proto_depIdxs = []int32{
	0, // 0: github.adamgarcia4.golearning.cassandra.gossip.v1.GossipDigestSynMsg.digests:type_name -> github.adamgarcia4.golearning.cassandra.gossip.v1.GossipDigest
	6, // 1: github.adamgarcia4.golearning.cassandra.gossip.v1.EndpointState.application_states:type_name -> github.adamgarcia4.golearning.cassandra.gossip.v1.EndpointState.ApplicationStatesEntry
	3, // 2: github.adamgarcia4.golearning.cassandra.gossip.v1.GossipDigestAck.endpoint_states:type_name -> github.adamgarcia4.golearning.cassandra.gossip.v1.EndpointState
	0, // 3: github.adamgarcia4.golearning.cassandra.gossip.v1.GossipDigestAck.request_digests:type_name -> github.adamgarcia4.golearning.cassandra.gossip.v1.GossipDigest
	3, // 4: github.adamgarcia4.golearning.cassandra.gossip.v1.GossipDigestAck2.endpoint_states:type_name -> github.adamgarcia4.golearning.cassandra.gossip.v1.EndpointState
	2, // 5: github.adamgarcia4.golearning.cassandra.gossip.v1.EndpointState.ApplicationStatesEntry.value:type_name -> github.adamgarcia4.golearning.cassandra.gossip.v1.ApplicationState
	1, // 6: github.adamgarcia4.golearning.cassandra.gossip.v1.GossipService.GossipDigestSyn:input_type -> github.adamgarcia4.golearning.cassandra.gossip.v1.GossipDigestSynMsg
	4, // 7: github.adamgarcia4.golearning.cassandra.gossip.v1.GossipService.GossipDigestSyn:output_type -> github.adamgarcia4.golearning.cassandra.gossip.v1.GossipDigestAck
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_gossip_v1_gossip_proto_init() }
func file_api_gossip_v1_gossip_proto_init() {
	if File_api_gossip_v1_gossip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gossip_v1_gossip_proto_rawDesc), len(file_api_gossip_v1_gossip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gossip_v1_gossip_proto_goTypes,
		DependencyIndexes: file_api_gossip_v1_gossip_proto_depIdxs,
		MessageInfos:      file_api_gossip_v1_gossip_proto_msgTypes,
	}.Build()
	File_api_gossip_v1_gossip_proto = out.File
	file_api_gossip_v1_gossip_proto_goTypes = nil
	file_api_gossip_v1_gossip_proto_depIdxs = nil
}
