# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  startA:
    cmds:
      - echo "Starting node A"
      - go run . --port=50051 --node-id=node-1
  startB:
    cmds:
      - echo "Starting node B (client mode)"
      - go run . --port=50052 --node-id=node-2 --target=127.0.0.1:50051
  init:
    deps:
      # - startA
      - startB
  kill:
    cmds:
      - lsof -t -i:50051 -i:50052 | xargs kill -9
  default:
    cmds:
      - go run . --port=50051 --node-id=node-1
    silent: true

  # Generate protobuf code from .proto files
  proto:
    desc: Generate Go code from protobuf definitions
    cmds:
      - echo "Generating protobuf code..."
      - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative api/gossip/v1/heartbeat.proto
      - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative api/gossip/v1/gossip.proto
      - echo "✅ Protobuf code generated successfully"
